### ISSUE TITLE
Diseño front HU7: Crear Periodo de recolecion

### ISSUE THREAD

**Issue by andresospina0000** [MariangelaNM/Coffee-Administration-UI#10]
- [ ] Como usuario, debo poder agregar un nuevo período de recolección de café con información como los el tipo de recoleccion,nombre,descrición,pago por cajuela y fecha (creación).

- [ ] Como usuario, debo poder ver la lista de períodos de recolección de café planificados y programados con su información asociada, para poder hacer seguimiento al proceso de producción.

- [ ] Como usuario, debo poder editar la información de un período de recolección de café existente, como su fecha de inicio y finalización o la variedad de café que se va a cosechar.

- [ ] Como usuario, debo poder eliminar un período de recolección de café existente si la información no es relevante o ha sido cancelado.

- [ ] La información sobre los períodos de recolección de café debe almacenarse en una base de datos segura y solo debe ser accesible para usuarios autorizados.				

![Image](https://user-images.githubusercontent.com/119467106/240760961-9eaa7646-df0a-47da-85c0-07e55bfed50d.jpg)

![Image](https://user-images.githubusercontent.com/119467106/240760969-c720ae54-2219-48b4-925c-7938218210f1.jpg)

![Image](https://user-images.githubusercontent.com/119467106/240760977-d98a2e1c-4138-479c-92d6-f128c3d140b2.jpg)
