### ISSUE TITLE
Diseño front HU2: Inicio de sesión

### ISSUE THREAD

**Issue by andresospina0000** [MariangelaNM/Coffee-Administration-UI#6]
## Descripción

Como usuario, quiero poder logearme en la aplicación

## Requerimientos

- https://github.com/MariangelaNM/Coffee-Administration-UI/issues/65
- [ ] Como usuario, quiero poder ingresar mi correo electrónico y contraseña en los campos del formulario de inicio de sesión.

- [ ] Como usuario, quiero recibir un mensaje de error si mi correo electrónico o contraseña son incorrectos.
![Image](https://user-images.githubusercontent.com/119467106/240703822-2a7c9aec-4cac-4771-8e46-5c0c0dc448e7.png)

- [ ] Como usuario, quiero ser redirigido al home si ingreso mi correo electrónico y contraseña correctamente.

- [ ] Como usuario, quiero tener la opción de recordar mi inicio de sesión para no tener que ingresar mi correo electrónico y contraseña cada vez que abro la aplicación.
