### ISSUE TITLE
Diseño front HU5: CRUD Zona

### ISSUE THREAD

**Issue by andresospina0000** [MariangelaNM/Coffee-Administration-UI#7]
- [ ] Como usuario, debo poder crear una nueva zona de producción, ingresando el nombre de la zona y la finca a la  que pertenece.

- [ ] Como usuario, debo poder ver una lista de todas las zonas de producción registradas en el sistema, con la opción de filtrar y buscar por diferentes criterios.

- [ ] Como usuario, debo poder editar los detalles de una zona de producción existente, para corregir información errónea o actualizar datos relevantes.

- [ ] Como usuario, debo poder eliminar una zona de producción existente, si ya no es utilizada por la empresa o si ya no es necesaria en el sistema.					

![Image](https://user-images.githubusercontent.com/119467106/240756772-ed87a3c5-ae8e-41bf-a0ce-ca8da5922bf8.jpg)

![Image](https://user-images.githubusercontent.com/119467106/240708583-f860bc87-bb81-4e20-aef8-e35d43344460.jpg)

![Image](https://user-images.githubusercontent.com/119467106/240709182-848508a3-31c2-4ada-a591-27e0d83a1b8f.jpg)
