### ISSUE TITLE
Diseño front HU4: CRUD Finca

### ISSUE THREAD

**Issue by andresospina0000** [MariangelaNM/Coffee-Administration-UI#8]
- [ ] Como usuario, debo poder ver una lista de todas las fincas registradas en el sistema, con la opción de filtrar .

- [ ] Como usuario, debo poder editar los detalles de una finca existente, para corregir información errónea o actualizar datos relevantes.

- [ ] Como usuario, debo poder eliminar una finca existente, si ya no es propiedad de la empresa o si ya no es necesaria en el sistema.

- [ ] Como usuario, debo poder crear una nueva finca, ingresando la información de la finca, como su nombre y ubicación.

- [ ] Como usuario, quiero que se guarde la fecha en que se registro la finca.

![Image](https://user-images.githubusercontent.com/119467106/240755998-0c7b460b-4775-46e6-a88c-6186f1cf0a6b.jpg)

![Image](https://user-images.githubusercontent.com/119467106/240756017-f269f708-46ae-4903-b334-e34ff795d73c.jpg)

![Image](https://user-images.githubusercontent.com/119467106/240756033-f6889d7d-73ea-4b4d-947a-6ca3b3b5f93e.jpg)
