### ISSUE TITLE
Diseño front HU6: CRUD recolector

### ISSUE THREAD

**Issue by andresospina0000** [MariangelaNM/Coffee-Administration-UI#9]
- [ ] Como usuario, debo poder agregar un nuevo recolector de café con su información personal, como nombre, número de identificación y número de teléfono.

- [ ] Como usuario, debo poder ver la lista de recolectores de café registrados en la finca con su información básica.

- [ ] Como usuario, debo poder editar la información de un recolector de café existente, como su número de teléfono o dirección.

- [ ] Como usuario, debo poder eliminar un recolector de café existente si ya no trabaja en la finca o si la información es incorrecta.

- [ ] La información de los recolectores de café debe almacenarse en una base de datos segura y solo debe ser accesible para usuarios autorizados.				

![Image](https://user-images.githubusercontent.com/119467106/240758139-8d202c3d-a0f8-4d53-be0e-ef086d6fbbf4.jpg)

![Image](https://user-images.githubusercontent.com/119467106/240758149-6d4c8b37-ecce-45ed-a135-6cd025dd9727.jpg)

![Image](https://user-images.githubusercontent.com/119467106/240758168-eef8b8c2-c643-4578-ad14-29925e3ff2fa.jpg)
